"""
rdc_recon.py -- offline RenderDoc capture analysis for segmentation-capture recon.

Run:
    set RDC_PATH=C:\\path\\to\\capture.rdc
    qrenderdoc.exe --python rdc_recon.py

Report is written to <capture>.recon.txt.

Goal: identify which depth-stencil target is Unreal's CustomDepth, using only
signals an injected DLL could also observe at runtime -- format, dimensions,
bind order, clear pattern, draw counts, stencil state. Debug names are reported
but deliberately never used as a discriminator, because they are stripped in
shipping builds.

Design note: this script does NOT use defensive getattr chains. An earlier
version did, and when a field name guess was wrong the chain returned None and
the report confidently printed "0 depth targets write stencil" instead of
failing. Wrong guess became wrong answer, silently. Field names here were
verified against the live API by rdc_probe_api.py; anything uncertain is
wrapped in a narrow try that REPORTS the failure rather than swallowing it.
"""

import os
import glob
from collections import OrderedDict

import renderdoc as rd

OUT = []


def emit(line=""):
    OUT.append(str(line))
    print(line)


def head(title):
    emit()
    emit("=" * 78)
    emit(title)
    emit("=" * 78)


def resolve_capture_path():
    p = os.environ.get("RDC_PATH", "").strip('"')
    if p and os.path.isfile(p):
        return p
    d = os.environ.get("RDC_DIR") or os.path.join(os.environ.get("TEMP", "."), "RenderDoc")
    hits = sorted(glob.glob(os.path.join(d, "*.rdc")), key=os.path.getmtime)
    if not hits:
        raise SystemExit("no capture found; set RDC_PATH or RDC_DIR")
    return hits[-1]


def flatten(actions, out=None):
    out = [] if out is None else out
    for a in actions:
        out.append(a)
        flatten(a.children, out)
    return out


# RenderDoc invents names like "2D Depth Target 1900" when a resource has no
# real debug name. Treat those as absent -- otherwise a shipping build looks
# fully annotated and we would wrongly conclude names are usable.
_AUTO_PREFIXES = (
    "Resource ", "Texture ", "Buffer ", "2D Depth Target ", "2D Render Target ",
    "2D Texture ", "3D Texture ", "1D Texture ", "Unnamed ", "Cube Texture ",
)


def looks_autogenerated(name):
    if not name:
        return True
    return any(name.startswith(p) for p in _AUTO_PREFIXES)


def analyze(path):
    head("CAPTURE")
    emit("file: %s" % path)

    cap = rd.OpenCaptureFile()
    if cap.OpenFile(path, "", None) != rd.ResultCode.Succeeded:
        raise SystemExit("could not open capture")
    if cap.LocalReplaySupport() != rd.ReplaySupport.Supported:
        raise SystemExit("local replay unsupported")
    result, ctrl = cap.OpenCapture(rd.ReplayOptions(), None)
    if result != rd.ResultCode.Succeeded:
        raise SystemExit("could not init replay: %s" % result)

    try:
        emit("API: %s" % ctrl.GetAPIProperties().pipelineType)

        textures = {t.resourceId: t for t in ctrl.GetTextures()}
        resources = {r.resourceId: r for r in ctrl.GetResources()}

        # ---- backbuffer -----------------------------------------------------
        head("BACKBUFFER")
        swap = [t for t in textures.values()
                if t.creationFlags & rd.TextureCategory.SwapBuffer]
        if not swap:
            emit("NO SwapBuffer-flagged texture found -- cannot establish full resolution")
            bb_w = bb_h = 0
        else:
            bb = swap[0]
            bb_w, bb_h = bb.width, bb.height
            for t in swap:
                emit("  %-18s %dx%d  %s" % (t.resourceId, t.width, t.height, t.format.Name()))
            emit("full resolution := %dx%d" % (bb_w, bb_h))

        # ---- depth-stencil inventory ----------------------------------------
        head("DEPTH-STENCIL INVENTORY")
        ds = [t for t in textures.values()
              if t.creationFlags & rd.TextureCategory.DepthTarget]

        emit("%-18s %-22s %12s %8s %8s %8s  %s"
             % ("resourceId", "format", "dims", "samples", "stencil", "fullres", "name"))
        emit("-" * 108)
        for t in sorted(ds, key=lambda x: -(x.width * x.height)):
            fmtname = t.format.Name()
            stencil = "S8" in fmtname or "S8X24" in fmtname or "G8" in fmtname
            fullres = (t.width, t.height) == (bb_w, bb_h)
            raw = resources[t.resourceId].name if t.resourceId in resources else ""
            emit("%-18s %-22s %12s %8d %8s %8s  %s"
                 % (t.resourceId, fmtname, "%dx%d" % (t.width, t.height),
                    t.msSamp, "yes" if stencil else "no",
                    "yes" if fullres else "no",
                    "<auto>" if looks_autogenerated(raw) else raw))

        candidates = [t for t in ds
                      if (t.width, t.height) == (bb_w, bb_h)
                      and ("S8" in t.format.Name() or "G8" in t.format.Name())]
        emit()
        emit("full-res depth targets with a stencil plane: %d" % len(candidates))

        # ---- action census, straight from the action list --------------------
        # ActionDescription.depthOut carries the bound depth target, so the whole
        # frame can be censused without replaying a single event. The previous
        # version called SetFrameEvent hundreds of times to learn this.
        head("PER-DEPTH-TARGET ACTION CENSUS")
        actions = flatten(ctrl.GetRootActions())
        emit("total actions: %d" % len(actions))

        stats = OrderedDict()

        def bucket(rid):
            if rid not in stats:
                stats[rid] = {"draws": 0, "clears": 0, "clear_eids": [],
                              "first": None, "last": None}
            return stats[rid]

        null = rd.ResourceId.Null()
        draws_total = 0
        draws_without_depth = 0

        for a in actions:
            dout = a.depthOut
            if a.flags & rd.ActionFlags.Drawcall:
                draws_total += 1
                if dout == null:
                    draws_without_depth += 1
                    continue
                b = bucket(dout)
                b["draws"] += 1
                b["first"] = a.eventId if b["first"] is None else b["first"]
                b["last"] = a.eventId
            if a.flags & rd.ActionFlags.ClearDepthStencil:
                rid = dout if dout != null else None
                if rid is None:
                    # Clears sometimes carry the target in outputs instead.
                    outs = [o for o in a.outputs if o != null]
                    rid = outs[0] if outs else null
                b = bucket(rid)
                b["clears"] += 1
                b["clear_eids"].append(a.eventId)

        emit("drawcalls: %d  (with a depth target: %d, without: %d)"
             % (draws_total, draws_total - draws_without_depth, draws_without_depth))
        emit()

        ordered = sorted(stats.items(), key=lambda kv: -kv[1]["draws"])
        emit("%-18s %8s %8s %14s %12s  %s"
             % ("depth target", "draws", "clears", "EID range", "dims", "format"))
        emit("-" * 96)
        for rid, s in ordered:
            t = textures.get(rid)
            emit("%-18s %8d %8d %14s %12s  %s"
                 % (rid, s["draws"], s["clears"],
                    "%s..%s" % (s["first"], s["last"]) if s["first"] is not None else "-",
                    "%dx%d" % (t.width, t.height) if t else "?",
                    t.format.Name() if t else "?"))
            if s["clear_eids"]:
                emit("%-18s   clear EIDs: %s" % ("", s["clear_eids"][:12]))

        # ---- stencil state, sampled per depth target -------------------------
        # Only a handful of draws per target need replaying, because stencil
        # state is a property of the pass, not of individual draws.
        head("STENCIL STATE PER DEPTH TARGET")
        emit("(sampling up to 12 draws per target; stencil state is a pass property)")
        emit()

        by_target = {}
        for a in actions:
            if not (a.flags & rd.ActionFlags.Drawcall):
                continue
            if a.depthOut == null:
                continue
            by_target.setdefault(a.depthOut, []).append(a)

        for rid, acts in sorted(by_target.items(), key=lambda kv: -len(kv[1])):
            step = max(1, len(acts) // 12)
            sample = acts[::step][:12]
            enabled = 0
            refs, wmasks, failures = set(), set(), 0

            for a in sample:
                try:
                    ctrl.SetFrameEvent(a.eventId, True)
                    dss = ctrl.GetD3D12PipelineState().outputMerger.depthStencilState
                    if dss.stencilEnable:
                        enabled += 1
                        for f in (dss.frontFace, dss.backFace):
                            refs.add(f.reference)
                            wmasks.add(f.writeMask)
                except Exception as e:
                    failures += 1
                    if failures == 1:
                        emit("  !! eid=%d state read failed: %r" % (a.eventId, e))

            t = textures.get(rid)
            emit("depth target %s  %s" % (rid, t.format.Name() if t else "?"))
            emit("    draws total        : %d   (sampled %d)" % (len(acts), len(sample)))
            emit("    stencilEnable      : %d / %d sampled" % (enabled, len(sample)))
            emit("    stencil writeMasks : %s" % (sorted(wmasks) if wmasks else "none"))
            emit("    stencil references : %s" % (sorted(refs) if refs else "none"))
            if failures:
                emit("    STATE READ FAILURES: %d" % failures)
            writes = enabled > 0 and any(w for w in wmasks)
            emit("    -> writes stencil  : %s" % ("YES" if writes else "no"))
            emit()

        # ---- debug names -----------------------------------------------------
        head("DEBUG NAME AVAILABILITY")
        real = [r for r in resources.values() if not looks_autogenerated(r.name)]
        emit("resources: %d total, %d with a non-autogenerated name" % (len(resources), len(real)))
        for r in real[:15]:
            emit("    %s" % r.name)
        emit()
        emit("verdict: debug names are %s"
             % ("PRESENT" if len(real) > len(resources) * 0.05
                else "STRIPPED (as expected for a shipping build)"))

    finally:
        ctrl.Shutdown()
        cap.Shutdown()


def main():
    path = resolve_capture_path()
    try:
        analyze(path)
    finally:
        rep = path + ".recon.txt"
        try:
            with open(rep, "w", encoding="utf-8") as f:
                f.write("\n".join(OUT))
            print("\n[report -> %s]" % rep)
        except Exception as e:
            print("could not write report: %s" % e)
    os._exit(0)


main()
